service: pedirPizzas

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrdersQueue
    PENDING_ORDER_QUEUE_NAME: PendingOrdersQueue
    COMPLETED_ORDERS_TABLE: CompletedOrdersTable
  iamRoleStatements:
   - Effect: Allow
     Action:
       - sqs:*
     Resource:
       Fn::GetAtt: [ "${self:provider.environment.PENDING_ORDER_QUEUE_NAME}", Arn ]
   - Effect: Allow
     Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem 
     Resource:
       Fn::GetAtt: [ "${self:provider.environment.COMPLETED_ORDERS_TABLE}", Arn ]


functions:
  verEstadoPedido:
    handler: handler.verPedido
    events:
      - http:
          method: get
          path: pedido/{orderId}
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: post
          path: pedido
  prepararPedido:
    handler: handler.prepararPedido
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PendingOrdersQueue
              - Arn
          batchSize: 1
  enviarPedido:
    handler: handler.enviarPedido
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - CompletedOrdersTable
              - StreamArn

      
resources:
  Resources:
    PendingOrdersQueue: 
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.PENDING_ORDER_QUEUE_NAME}
    CompletedOrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "orderId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "orderId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.COMPLETED_ORDERS_TABLE}
        StreamSpecification:
          StreamViewType: NEW_IMAGE