service: pedirPizzas

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrdersQueue
    PENDING_ORDER_QUEUE_NAME: PendingOrdersQueue
  iamRoleStatements:
   - Effect: Allow
     Action:
       - sqs:*
     Resource:
       Fn::GetAtt: [ "${self:provider.environment.PENDING_ORDER_QUEUE_NAME}", Arn ]


functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: post
          path: pedido
  prepararPedido:
    handler: handler.prepararPedido
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PendingOrdersQueue
              - Arn
          batchSize: 1
      
resources:
  Resources:
    PendingOrdersQueue: 
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.PENDING_ORDER_QUEUE_NAME}